### ISSUE TITLE
Upstream possible?

### ISSUE THREAD

**Issue by nat-418** [aksdb/caddy-cgi#11]
Is there a way to get this upstreamed into Caddy so that we don't have to make a custom build to use it?

**Comment by nat-418** [comment]
I found your repo through this discussion:

https://caddy.community/t/how-to-activate-cgi-in-v2/11816/2

> The plugin maintainer needs to do that. You can ask them to by opening an issue on github. They just need to make an account on [caddyserver.com](http://caddyserver.com/) and then register their plugin.

**Comment by aksdb** [comment]
But this is talking about registering the plugin. Which I already did when I forked this (at least 2 years ago): https://caddyserver.com/download?package=github.com%2Faksdb%2Fcaddy-cgi%2Fv2

**Comment by nat-418** [comment]
> But this is talking about registering the plugin. Which I already did when I forked this (at least 2 years ago): https://caddyserver.com/download?package=github.com%2Faksdb%2Fcaddy-cgi%2Fv2 ![image](https://user-images.githubusercontent.com/2435857/240164557-60b35fcb-6ee1-4e53-b80f-1440cf601e84.png)

I'm sorry to bother you. When searching for a way to use CGI with Caddy, I somehow did not come across that search result. Thank you for your time and work.
