### ISSUE TITLE
module declares its path as: github.com/jung-kurt/caddy-cgi

### ISSUE THREAD

**Issue by xoid** [aksdb/caddy-cgi#14]
trying to compile caddy
xcaddy build --with github.com/aksdb/caddy-cgi

I got an error:
2023/10/16 13:01:46 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/aksdb/caddy-cgi github.com/caddyserver/caddy/v2
go: downloading github.com/aksdb/caddy-cgi v1.11.4
go: github.com/aksdb/caddy-cgi upgrade => v1.11.4
go get: github.com/aksdb/caddy-cgi@v1.11.4: parsing go.mod:
        module declares its path as: github.com/jung-kurt/caddy-cgi
                but was required as: github.com/aksdb/caddy-cgi
2023/10/16 13:01:49 [FATAL] exit status 1

Please add short installation howto to README

**Comment by Flameborn** [comment]
Hi @xoid

For Caddy 2, you need to define it as github.com/aksdb/caddy-cgi/v2. V1 is, I believe, for Caddy 1.
