### ISSUE TITLE
Possible to do an nph option?

### ISSUE THREAD

**Issue by jum** [aksdb/caddy-cgi#7]
Is it possible to add an nph option to enable scripts that perform their own header processing?

**Comment by aksdb** [comment]
@jum Do you have a specific example CGI script that currently doesn't work? AFAIK you can already set headers from within CGI and they will simply be passed along.

**Comment by jum** [comment]
For example the following noh-trace.cgi does work with apache but not with the caddy plugin:

#!/usr/bin/perl -w

# nph-trace.cgi, output the traceroute to a host a line at at time.
# ***@***.***

use strict;
use warnings;
use CGI qw(:standard);
use CGI::Carp qw(fatalsToBrowser);

my @spammers = ("193.251.40.5");

$SIG{"PIPE"} = 'DEFAULT';

my $real_remote = $ENV{'HTTP_X_FORWARDED_FOR'};
if ($real_remote eq '') {
	$real_remote = remote_host();
}

if (grep(/^@{[quotemeta($real_remote)]}$/, @spammers)) {
        print header(-nph=>1);
        print start_html(-title=>"traceroute/tracepath", -BGCOLOR=>"white"),
		img({src=>'/img/hannet2.gif'}),
                h1("traceroute/tracepath");
        print 'Not available', br;
	print a({href=>'/'}, 'back to the home page');
	print end_html;
        exit 0
}

if (param()) {
	my $arg = param('addr');
	print header(-nph=>1, -expires=>'+5m');
	my $v6 = "";
	if (param('ipv6') && param('ipv6') eq 'on') {
		$v6 = "6";
	}
	my $cmd = "";
	if (param('method') eq 'traceroute') {
		$cmd = 'traceroute';
	} elsif (param('method') eq 'tracepath') {
		$cmd = 'tracepath';
	} else {
		$cmd = 'traceroute';
	}
	$cmd .= $v6;
	print start_html(-title=>"$cmd to $arg", -BGCOLOR=>"white"),
		img({src=>'/img/hannet2.gif'}),
		h1("$cmd to $arg"), hr;
	if ($arg !~ /^[0-9a-zA-Z\.:][0-9a-zA-Z\.:-]*$/) {
		print "Illegal chars in argument";
	} else {
		$| = 1;
		print "<PRE>";
		system("$cmd $arg 2>&1");
		print "</PRE>";
	}
} else {
	print header(-nph=>1, -expires=>'+5m');
	print start_html(-title=>"traceroute/tracepath", -BGCOLOR=>"white"),
		img({src=>'/img/hannet2.gif'}),
		h1("traceroute/tracepath");
}
print hr, start_multipart_form;
print "IP Address: ", textfield(-name=>'addr', -size=>64, -maxlength=>255,
	-default=>$real_remote);
print submit(-name=>'start', -value=>' Start '), "<br>\n";
my $ipv6 = $real_remote =~ /:/;
print "Method: ", popup_menu(-name=>'method',
	-values=>['traceroute', 'tracepath']), "\n";
print checkbox(-name=>'ipv6', -checked=>$ipv6, -label=>'use IPv6'), "<br>\n";
print end_form;
print a({href=>'https://www.han.de/'}, 'back to the HanNet home page');
print end_html;

Am 28. August 2022 03:14:02 GMT-06:00 schrieb Andreas Schneider ***@***.***>:
***@***.*** Do you have a specific example CGI script that currently doesn't work? AFAIK you can already set headers from within CGI and they will simply be passed along.

**Comment by aksdb** [comment]
I don't think this is feasible without a lot of effort. The whole handling of CGI scripts is done as a sub-set of HTTP, so we can't just "pass through" raw responses.

Why would this be necessary, though? The only advantage I can see is that you could write a custom `HTTP <status> <text>` line. You can still set the status with the `Status` header, though. All the other headers get passed through already as well.

Aside from that possible problem with the status header, the script you provided works for me:
![image](https://user-images.githubusercontent.com/2435857/188306342-43909cdd-78c7-4f11-9627-841628f2e067.png)

**Comment by jum** [comment]
The script relies on the nph- feature mostly to make the output unbuffered, so you can see the traceroute while it is happening.  As this was an exotic feature 30 years ago when this script was written, there more standard ways to do that now, I will see what I can come up with.

Am 4. September 2022 03:15:28 GMT-06:00 schrieb Andreas Schneider ***@***.***>:

**Comment by aksdb** [comment]
That's a valid use-case, I have to admit. I'll look into it once more when I have time. I don't have high hopes for it though. In Go we have control over the outgoing stream by calling `Flush()` whenever we need to omit the buffer ... but there is no way (that I know of) to disable the buffer completely. Maybe I can rework / extend the CGI handler to flush whenever it read something from `stdout` of the running executable.

No promises yet. As usual, it's very likely technically possible, but may require too much rework to be worth it.

If (!) it turns out to work the way I expect, then it would likely be an option like "unbuffered" or something. So the header handling will stay the way it is now, but all output from the script would be passed along ASAP. We'll see :slightly_smiling_face:

**Comment by jum** [comment]
I have just tested it, and it works nicely. I simply removed the nph options from the perl code and added the unbuffered_output option for this particular script and I can see the trace route steps while they happen. Thank you.
